# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Audiophile App"
  lane :beta_test do
    
      firebase_app_distribution(
          app: "1:329324834777:ios:2dcf53b637a65b1fa8f3c8"
          firebase_cli_token: "1//03Y9CT9MMjabUCgYIARAAGAMSNwF-L9IrqWiqbe7A9r5UXSX3uo3tiRQwEpF5UEoDJAt21AkIN_vh74QJyojwm81HKMkwwFebk48",
          testers: "c.j91350@gmail.com",
          release_notes: "Deployment test release of Audiophile app ",
      )
  end
end
