# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Audiophile App"
  lane :beta_test do
    
      firebase_app_distribution(
          app: IOS_APP_ID
          firebase_cli_token: FIREBASE_CLI_TOKEN,
          testers: EMAIL_TESTERS,
          release_notes: "Deployment test release of Audiophile app ",
      )
  end
end
