default_platform(:android)

platform :android do
  desc "Audiophile App"
  lane :beta_test do
      # build_android_app(...)
      # # build_android_app is a built-in fastlane action.
      firebase_app_distribution(
          app: "1:329324834777:android:6a6803656beb94dfa8f3c8",
          firebase_cli_token: "1//03Y9CT9MMjabUCgYIARAAGAMSNwF-L9IrqWiqbe7A9r5UXSX3uo3tiRQwEpF5UEoDJAt21AkIN_vh74QJyojwm81HKMkwwFebk48",
          testers: "c.j91350@gmail.com",
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
          release_notes: "Deployment test of app"
      )
  end
end
